/**
 * @api {post} /api/udemy Post Udemy Course
 * @apiName PostUdemyCourse
 * @apiGroup Courses
 *  
 * @apiHeader {string} Content-Type the type of content being sent
 * @apiHeader {string} token User's token for authorization
 * 
 * @apiHeaderExample {json} Header-Example:
 * {
 *  "Content-Type": "application/json",
 *  "authorization": "sjvbhoi8uh87hfv8ogbo8iugy387gfofebcvudfbvouydyhf8377fg"
 * }
 * 
 * @apiParam {String} link The link of the course you want to create
 * 
 * @apiParamExample {json} Course-Post-Example:
 * {
 * 	 "link": "https://www.udemy.com/course/complete-react-developer-zero-to-mastery/"
 * }
 * 
 * @apiSuccess (201) {Object} Course The course generated by the posted link
 * 
 * @apiSuccessExample Success-Response:
 * HTTP/1.1 201 Created
 * {
 *   "id": 4,
 *   "name": "JavaScript Animations with GreenSock (GSAP)",
 *   "link": "https://www.udemy.com/course/javascript-animations-using-greensock/",
 *   "description": null,
 *   "category": null,
 *   "creator_id": 2,
 *   "foreign_rating": null,
 *   "foreign_instructors": "David Sharkey"
 * }
 * 
 * @apiSuccess (200) {Object} Course The course generated by the posted link, along with a message that the course already exists
 * 
 * @apiSuccessExample Success-Response:
 * HTTP/1.1 200 OK
 * {
 *   "message": "Course already exists in Database",
 *   "course": {
 *     "id": 4,
 *     "name": "JavaScript Animations with GreenSock (GSAP)",
 *     "link": "https://www.udemy.com/course/javascript-animations-using-greensock/",
 *     "description": null,
 *     "category": null,
 *     "creator_id": 2,
 *     "foreign_rating": null,
 *     "foreign_instructors": "David Sharkey"
 *   }
 * }
 * 
 * @apiError (400) {Object} Missing-Link The course link is absent
 * 
 * @apiErrorExample 400-Course-Missing:
 * HTTP/1.1 400 Bad Request
 * {
 *   "message": "No link present in post body"
 * }
 * 
 * @apiError (400) {String} Not-Udemy The course link is not from Udemy
 * 
 * @apiErrorExample 400-Not-Udemy:
 * HTTP/1.1 400 Bad Request
 * {
 *   "message": "Not a Udemy Link"
 * }
 * 
 * @apiError (401) {Object} bad-request-error The authorization header is absent
 * 
 * @apiErrorExample 401-Error-Response:
 * HTTP/1.1 401 Bad Request
 * {
 *  "message": "Forbidden Access!"
 * }
 * 
 * @apiError (401) {Object} bad-request-error The authorization is invalid
 * 
 * @apiErrorExample 401-Error-Response:
 * HTTP/1.1 401 Bad Request
 * {
 *  "message": "Invalid Credentials"
 * }
 * 
 * @apiError (500) {Object} Retrieve-Details-Error Could not retrieve course details
 * 
 * @apiErrorExample 500-Retrieve-Details-Error:
 * HTTP/1.1 500 Internal Server Error
 * {
 *  "message": "error: could not retrieve course details"
 * }
 * 
 * @apiError (500) {Object} Add-Course-Error Could not add course
 * 
 * @apiErrorExample 500-Add-Course-Error:
 * HTTP/1.1 500 Internal Server Error
 * {
 *  "message": "internal error, could not add course"
 * }
 * 
 * @apiError (500) {Object} Retrieve-Course-Error could not retrieve course
 * 
 * @apiErrorExample 500-Retrieve-Course-Error:
 * HTTP/1.1 500 Internal Server Error
 * {
 *  "message": "error: could not retrieve course"
 * }
 * 
 * @apiError (500) {Object} Find-User-Error Could not find user to add course for
 * 
 * @apiErrorExample 500-Find-User-Error:
 * HTTP/1.1 500 Internal Server Error
 * {
 *  "message": "Could not find user to add Udemy course for"
 * }
 * 
 */